/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import java.util.*;
import joosc.analysis.*;

public final class ABlockStm extends PStm
{
    private final LinkedList _stmts_ = new TypedLinkedList(new Stmts_Cast());

    public ABlockStm()
    {
    }

    public ABlockStm(
        List _stmts_)
    {
        {
            this._stmts_.clear();
            this._stmts_.addAll(_stmts_);
        }

    }
    public Object clone()
    {
        return new ABlockStm(
            cloneList(_stmts_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlockStm(this);
    }

    public LinkedList getStmts()
    {
        return _stmts_;
    }

    public void setStmts(List list)
    {
        _stmts_.clear();
        _stmts_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_stmts_);
    }

    void removeChild(Node child)
    {
        if(_stmts_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _stmts_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Stmts_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PStm node = (PStm) o;

            if((node.parent() != null) &&
                (node.parent() != ABlockStm.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ABlockStm.this))
            {
                node.parent(ABlockStm.this);
            }

            return node;
        }
    }
}
