/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import java.util.*;
import joosc.analysis.*;

public final class AExternClass extends PExternClass
{
    private PClassmods _classmods_;
    private TIdentifier _identifier_;
    private PExtension _extension_;
    private TStringconst _stringconst_;
    private final LinkedList _constructors_ = new TypedLinkedList(new Constructors_Cast());
    private final LinkedList _methods_ = new TypedLinkedList(new Methods_Cast());

    public AExternClass()
    {
    }

    public AExternClass(
        PClassmods _classmods_,
        TIdentifier _identifier_,
        PExtension _extension_,
        TStringconst _stringconst_,
        List _constructors_,
        List _methods_)
    {
        setClassmods(_classmods_);

        setIdentifier(_identifier_);

        setExtension(_extension_);

        setStringconst(_stringconst_);

        {
            this._constructors_.clear();
            this._constructors_.addAll(_constructors_);
        }

        {
            this._methods_.clear();
            this._methods_.addAll(_methods_);
        }

    }
    public Object clone()
    {
        return new AExternClass(
            (PClassmods) cloneNode(_classmods_),
            (TIdentifier) cloneNode(_identifier_),
            (PExtension) cloneNode(_extension_),
            (TStringconst) cloneNode(_stringconst_),
            cloneList(_constructors_),
            cloneList(_methods_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExternClass(this);
    }

    public PClassmods getClassmods()
    {
        return _classmods_;
    }

    public void setClassmods(PClassmods node)
    {
        if(_classmods_ != null)
        {
            _classmods_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _classmods_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public PExtension getExtension()
    {
        return _extension_;
    }

    public void setExtension(PExtension node)
    {
        if(_extension_ != null)
        {
            _extension_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _extension_ = node;
    }

    public TStringconst getStringconst()
    {
        return _stringconst_;
    }

    public void setStringconst(TStringconst node)
    {
        if(_stringconst_ != null)
        {
            _stringconst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _stringconst_ = node;
    }

    public LinkedList getConstructors()
    {
        return _constructors_;
    }

    public void setConstructors(List list)
    {
        _constructors_.clear();
        _constructors_.addAll(list);
    }

    public LinkedList getMethods()
    {
        return _methods_;
    }

    public void setMethods(List list)
    {
        _methods_.clear();
        _methods_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_classmods_)
            + toString(_identifier_)
            + toString(_extension_)
            + toString(_stringconst_)
            + toString(_constructors_)
            + toString(_methods_);
    }

    void removeChild(Node child)
    {
        if(_classmods_ == child)
        {
            _classmods_ = null;
            return;
        }

        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_extension_ == child)
        {
            _extension_ = null;
            return;
        }

        if(_stringconst_ == child)
        {
            _stringconst_ = null;
            return;
        }

        if(_constructors_.remove(child))
        {
            return;
        }

        if(_methods_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_classmods_ == oldChild)
        {
            setClassmods((PClassmods) newChild);
            return;
        }

        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(_extension_ == oldChild)
        {
            setExtension((PExtension) newChild);
            return;
        }

        if(_stringconst_ == oldChild)
        {
            setStringconst((TStringconst) newChild);
            return;
        }

        for(ListIterator i = _constructors_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator i = _methods_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Constructors_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PExternConstructor node = (PExternConstructor) o;

            if((node.parent() != null) &&
                (node.parent() != AExternClass.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AExternClass.this))
            {
                node.parent(AExternClass.this);
            }

            return node;
        }
    }

    private class Methods_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PExternMethod node = (PExternMethod) o;

            if((node.parent() != null) &&
                (node.parent() != AExternClass.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AExternClass.this))
            {
                node.parent(AExternClass.this);
            }

            return node;
        }
    }
}
