/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import java.util.*;
import joosc.analysis.*;

public final class AVoidType extends PType
{

    public AVoidType()
    {
    }
    public Object clone()
    {
        return new AVoidType();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVoidType(this);
    }

    public String toString()
    {
        return "";
    }

    void removeChild(Node child)
    {
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }
}
