/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import java.util.*;
import joosc.analysis.*;

public final class AArgumentList extends PArgumentList
{
    private final LinkedList _exp_ = new TypedLinkedList(new Exp_Cast());

    public AArgumentList()
    {
    }

    public AArgumentList(
        List _exp_)
    {
        {
            this._exp_.clear();
            this._exp_.addAll(_exp_);
        }

    }

    public AArgumentList(
        XPExp _exp_)
    {
        if(_exp_ != null)
        {
            while(_exp_ instanceof X1PExp)
            {
                this._exp_.addFirst(((X1PExp) _exp_).getPExp());
                _exp_ = ((X1PExp) _exp_).getXPExp();
            }
            this._exp_.addFirst(((X2PExp) _exp_).getPExp());
        }

    }
    public Object clone()
    {
        return new AArgumentList(
            cloneList(_exp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgumentList(this);
    }

    public LinkedList getExp()
    {
        return _exp_;
    }

    public void setExp(List list)
    {
        _exp_.clear();
        _exp_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_exp_);
    }

    void removeChild(Node child)
    {
        if(_exp_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _exp_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Exp_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PExp node = (PExp) o;

            if((node.parent() != null) &&
                (node.parent() != AArgumentList.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AArgumentList.this))
            {
                node.parent(AArgumentList.this);
            }

            return node;
        }
    }
}
