/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import java.util.*;
import joosc.analysis.*;

public final class ADefaultRelExp extends PRelExp
{
    private PAddExp _addExp_;

    public ADefaultRelExp()
    {
    }

    public ADefaultRelExp(
        PAddExp _addExp_)
    {
        setAddExp(_addExp_);

    }
    public Object clone()
    {
        return new ADefaultRelExp(
            (PAddExp) cloneNode(_addExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefaultRelExp(this);
    }

    public PAddExp getAddExp()
    {
        return _addExp_;
    }

    public void setAddExp(PAddExp node)
    {
        if(_addExp_ != null)
        {
            _addExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _addExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_addExp_);
    }

    void removeChild(Node child)
    {
        if(_addExp_ == child)
        {
            _addExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_addExp_ == oldChild)
        {
            setAddExp((PAddExp) newChild);
            return;
        }

    }
}
