/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import java.util.*;
import joosc.analysis.*;

public final class AModMultExp extends PMultExp
{
    private PMultExp _left_;
    private TMod _mod_;
    private PUnaryExp _right_;

    public AModMultExp()
    {
    }

    public AModMultExp(
        PMultExp _left_,
        TMod _mod_,
        PUnaryExp _right_)
    {
        setLeft(_left_);

        setMod(_mod_);

        setRight(_right_);

    }
    public Object clone()
    {
        return new AModMultExp(
            (PMultExp) cloneNode(_left_),
            (TMod) cloneNode(_mod_),
            (PUnaryExp) cloneNode(_right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModMultExp(this);
    }

    public PMultExp getLeft()
    {
        return _left_;
    }

    public void setLeft(PMultExp node)
    {
        if(_left_ != null)
        {
            _left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _left_ = node;
    }

    public TMod getMod()
    {
        return _mod_;
    }

    public void setMod(TMod node)
    {
        if(_mod_ != null)
        {
            _mod_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _mod_ = node;
    }

    public PUnaryExp getRight()
    {
        return _right_;
    }

    public void setRight(PUnaryExp node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_left_)
            + toString(_mod_)
            + toString(_right_);
    }

    void removeChild(Node child)
    {
        if(_left_ == child)
        {
            _left_ = null;
            return;
        }

        if(_mod_ == child)
        {
            _mod_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_left_ == oldChild)
        {
            setLeft((PMultExp) newChild);
            return;
        }

        if(_mod_ == oldChild)
        {
            setMod((TMod) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((PUnaryExp) newChild);
            return;
        }

    }
}
