/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import java.util.*;
import joosc.analysis.*;

public final class ANoncharCastExp extends PCastExp
{
    private TLPar _lPar_;
    private PExp _exp_;
    private TRPar _rPar_;
    private PUnaryExpNotMinus _unaryExpNotMinus_;

    public ANoncharCastExp()
    {
    }

    public ANoncharCastExp(
        TLPar _lPar_,
        PExp _exp_,
        TRPar _rPar_,
        PUnaryExpNotMinus _unaryExpNotMinus_)
    {
        setLPar(_lPar_);

        setExp(_exp_);

        setRPar(_rPar_);

        setUnaryExpNotMinus(_unaryExpNotMinus_);

    }
    public Object clone()
    {
        return new ANoncharCastExp(
            (TLPar) cloneNode(_lPar_),
            (PExp) cloneNode(_exp_),
            (TRPar) cloneNode(_rPar_),
            (PUnaryExpNotMinus) cloneNode(_unaryExpNotMinus_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANoncharCastExp(this);
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PExp getExp()
    {
        return _exp_;
    }

    public void setExp(PExp node)
    {
        if(_exp_ != null)
        {
            _exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exp_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public PUnaryExpNotMinus getUnaryExpNotMinus()
    {
        return _unaryExpNotMinus_;
    }

    public void setUnaryExpNotMinus(PUnaryExpNotMinus node)
    {
        if(_unaryExpNotMinus_ != null)
        {
            _unaryExpNotMinus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _unaryExpNotMinus_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lPar_)
            + toString(_exp_)
            + toString(_rPar_)
            + toString(_unaryExpNotMinus_);
    }

    void removeChild(Node child)
    {
        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_exp_ == child)
        {
            _exp_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

        if(_unaryExpNotMinus_ == child)
        {
            _unaryExpNotMinus_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        if(_unaryExpNotMinus_ == oldChild)
        {
            setUnaryExpNotMinus((PUnaryExpNotMinus) newChild);
            return;
        }

    }
}
