/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import java.util.*;
import joosc.analysis.*;

public final class ATmpIdentifierList extends PIdentifierList
{
    private TIdentifier _identifier_;
    private final LinkedList _identifierListTail_ = new TypedLinkedList(new IdentifierListTail_Cast());

    public ATmpIdentifierList()
    {
    }

    public ATmpIdentifierList(
        TIdentifier _identifier_,
        List _identifierListTail_)
    {
        setIdentifier(_identifier_);

        {
            this._identifierListTail_.clear();
            this._identifierListTail_.addAll(_identifierListTail_);
        }

    }

    public ATmpIdentifierList(
        TIdentifier _identifier_,
        XPIdentifierListTail _identifierListTail_)
    {
        setIdentifier(_identifier_);

        if(_identifierListTail_ != null)
        {
            while(_identifierListTail_ instanceof X1PIdentifierListTail)
            {
                this._identifierListTail_.addFirst(((X1PIdentifierListTail) _identifierListTail_).getPIdentifierListTail());
                _identifierListTail_ = ((X1PIdentifierListTail) _identifierListTail_).getXPIdentifierListTail();
            }
            this._identifierListTail_.addFirst(((X2PIdentifierListTail) _identifierListTail_).getPIdentifierListTail());
        }

    }
    public Object clone()
    {
        return new ATmpIdentifierList(
            (TIdentifier) cloneNode(_identifier_),
            cloneList(_identifierListTail_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATmpIdentifierList(this);
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public LinkedList getIdentifierListTail()
    {
        return _identifierListTail_;
    }

    public void setIdentifierListTail(List list)
    {
        _identifierListTail_.clear();
        _identifierListTail_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_identifier_)
            + toString(_identifierListTail_);
    }

    void removeChild(Node child)
    {
        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_identifierListTail_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        for(ListIterator i = _identifierListTail_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class IdentifierListTail_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PIdentifierListTail node = (PIdentifierListTail) o;

            if((node.parent() != null) &&
                (node.parent() != ATmpIdentifierList.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ATmpIdentifierList.this))
            {
                node.parent(ATmpIdentifierList.this);
            }

            return node;
        }
    }
}
