/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

public final class TFinally extends Token
{
    public TFinally()
    {
        super.setText("finally");
    }

    public TFinally(int line, int pos)
    {
        super.setText("finally");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TFinally(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFinally(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TFinally text.");
    }
}
