/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

public final class TSuper extends Token
{
    public TSuper()
    {
        super.setText("super");
    }

    public TSuper(int line, int pos)
    {
        super.setText("super");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSuper(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSuper(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSuper text.");
    }
}
