/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

public final class X1PExp extends XPExp
{
    private XPExp _xPExp_;
    private PExp _pExp_;

    public X1PExp()
    {
    }

    public X1PExp(
        XPExp _xPExp_,
        PExp _pExp_)
    {
        setXPExp(_xPExp_);
        setPExp(_pExp_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPExp getXPExp()
    {
        return _xPExp_;
    }

    public void setXPExp(XPExp node)
    {
        if(_xPExp_ != null)
        {
            _xPExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPExp_ = node;
    }

    public PExp getPExp()
    {
        return _pExp_;
    }

    public void setPExp(PExp node)
    {
        if(_pExp_ != null)
        {
            _pExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pExp_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPExp_ == child)
        {
            _xPExp_ = null;
        }

        if(_pExp_ == child)
        {
            _pExp_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPExp_) +
            toString(_pExp_);
    }
}
