/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

public final class X1PExternConstructor extends XPExternConstructor
{
    private XPExternConstructor _xPExternConstructor_;
    private PExternConstructor _pExternConstructor_;

    public X1PExternConstructor()
    {
    }

    public X1PExternConstructor(
        XPExternConstructor _xPExternConstructor_,
        PExternConstructor _pExternConstructor_)
    {
        setXPExternConstructor(_xPExternConstructor_);
        setPExternConstructor(_pExternConstructor_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPExternConstructor getXPExternConstructor()
    {
        return _xPExternConstructor_;
    }

    public void setXPExternConstructor(XPExternConstructor node)
    {
        if(_xPExternConstructor_ != null)
        {
            _xPExternConstructor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPExternConstructor_ = node;
    }

    public PExternConstructor getPExternConstructor()
    {
        return _pExternConstructor_;
    }

    public void setPExternConstructor(PExternConstructor node)
    {
        if(_pExternConstructor_ != null)
        {
            _pExternConstructor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pExternConstructor_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPExternConstructor_ == child)
        {
            _xPExternConstructor_ = null;
        }

        if(_pExternConstructor_ == child)
        {
            _pExternConstructor_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPExternConstructor_) +
            toString(_pExternConstructor_);
    }
}
