/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

public final class X1PIdentifierListTail extends XPIdentifierListTail
{
    private XPIdentifierListTail _xPIdentifierListTail_;
    private PIdentifierListTail _pIdentifierListTail_;

    public X1PIdentifierListTail()
    {
    }

    public X1PIdentifierListTail(
        XPIdentifierListTail _xPIdentifierListTail_,
        PIdentifierListTail _pIdentifierListTail_)
    {
        setXPIdentifierListTail(_xPIdentifierListTail_);
        setPIdentifierListTail(_pIdentifierListTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPIdentifierListTail getXPIdentifierListTail()
    {
        return _xPIdentifierListTail_;
    }

    public void setXPIdentifierListTail(XPIdentifierListTail node)
    {
        if(_xPIdentifierListTail_ != null)
        {
            _xPIdentifierListTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPIdentifierListTail_ = node;
    }

    public PIdentifierListTail getPIdentifierListTail()
    {
        return _pIdentifierListTail_;
    }

    public void setPIdentifierListTail(PIdentifierListTail node)
    {
        if(_pIdentifierListTail_ != null)
        {
            _pIdentifierListTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pIdentifierListTail_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPIdentifierListTail_ == child)
        {
            _xPIdentifierListTail_ = null;
        }

        if(_pIdentifierListTail_ == child)
        {
            _pIdentifierListTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPIdentifierListTail_) +
            toString(_pIdentifierListTail_);
    }
}
