/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

public final class X2PFormalListTail extends XPFormalListTail
{
    private PFormalListTail _pFormalListTail_;

    public X2PFormalListTail()
    {
    }

    public X2PFormalListTail(
        PFormalListTail _pFormalListTail_)
    {
        setPFormalListTail(_pFormalListTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PFormalListTail getPFormalListTail()
    {
        return _pFormalListTail_;
    }

    public void setPFormalListTail(PFormalListTail node)
    {
        if(_pFormalListTail_ != null)
        {
            _pFormalListTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pFormalListTail_ = node;
    }

    void removeChild(Node child)
    {
        if(_pFormalListTail_ == child)
        {
            _pFormalListTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pFormalListTail_);
    }
}
