#!/bin/sh

# uncomment the next line to see exactly what happens
# set -x


#export JAVADIR=/usr/local/jdk1.4.2/
#export PATH=..:${JAVADIR}/bin:${PATH}
#export CLASSPATH=.:$WIGDIR/wig10-classes.jar:${CLASSPATH}

root_dir=`pwd`

for bench in `cat $1 | cut -f1 | xargs echo`
  do
  bench_dir=`grep $bench $1 | cut -f2`
  bench_main=`grep $bench $1 | cut -f3`
  echo CLEANING ${bench} ${bench_dir} ${bench_main}
  
  cd ${bench_dir}

  find . -type f -name '*.c' | xargs rm -f
  find . -type f -name '*.cgi' | xargs rm -f
  find . -type f -name '*.h' | xargs rm -f

  for compiler in wig4 wig10 wig18 pwig lkwig
    do
    rm -rf ${compiler}
  done
  
  cd ${root_dir}

  echo
done

rm -f index.html

find . -type f | grep '~' | xargs rm -f
