#!/bin/sh

# uncomment the next line to see exactly what happens
# set -x

# command line inputs:
# $1 : benchmark list filename

# if you don't have WIGDIR defined in your environment variable:
# please uncomment the next line and set it to actual path of wig
#export WIGDIR=$HOME/cs520/2007/public_html/wig

compilers="wig4 wig10 wig18 lkwig pwig"

root_dir=`pwd`

for bench in `cat $1 | cut -f1 | xargs echo`
  do
  bench_dir=`grep $bench $1 | cut -f2`
  bench_main=`grep $bench $1 | cut -f3`
  echo BENCHMARK ${bench} ${bench_dir} ${bench_main}
  
  cd ${bench_dir}
  cp ${bench_main}.wig  ${WIGDIR}/bin/
  
  for compiler in ${compilers}
    do

    echo "========== COMPILATION WITH ${compiler} STARTED"
    cd ${WIGDIR}/bin/
    ${compiler} ${bench_main}.wig
    if [ ${compile}!="lkwig" ]; then
    if [ -e "${bench_main}.c" ]; then
	if [ -e "${bench_main}.install" ]; then
	    cd ${root_dir}
	    cd ${bench_dir}
	    if [ ! -d "${compiler}" ]; then
		    mkdir ${compiler}
		fi
	    mv ${WIGDIR}/bin/${bench_main}.c ${compiler}/
	    chmod 744 ${WIGDIR}/bin/${bench_main}.install
	    mv ${WIGDIR}/bin/${bench_main}.install ${compiler}/
	    if [ -e "${bench_main}_run.h" ]; then
		    mv ${WIGDIR}/bin/${bench_main}_run.h ${compiler}/
	    fi
	    echo "========== COMPILATION WITH ${compiler} FINISHED"
	else
	    rm -f ${bench_main}.c
	    echo "========== COMPILATION WITH ${compiler} ABORTED"
	fi
    else
	rm -f ${bench_main}.install
	echo "========== COMPILATION WITH ${compiler} ABORTED"
    fi  
   	else
    #for lkwig
    cd ${WIGDIR}/bin/
    if [ -e "${bench_main}.pl" ]; then
    	cd ${root_dir}
	    cd ${bench_dir}
	    if [ ! -d "${compiler}" ]; then
		    mkdir ${compiler}
		fi
	    chmod 744 ${WIGDIR}/bin/${bench_main}.pl
	    mv ${WIGDIR}/bin/${bench_main}.pl ${compiler}/
	    echo "========== COMPILATION WITH ${compiler} FINISHED"
	else
	    echo "========== COMPILATION WITH ${compiler} ABORTED"  
    fi
    fi  
  done
    
    cd ${root_dir}
    cd ${WIGDIR}/bin
    if [ -e "${bench_main}.wig" ]; then
       rm -f ${bench_main}.wig
    fi 
    if [ -e "${bench_main}_run.h" ]; then
       rm -f ${bench_main}_run.h
    fi 
    if [ -e "${bench_main}.pl" ]; then
       rm -f ${bench_main}.pl
    fi 

    
  cd ${root_dir}

  echo
done
