/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

public final class TThis extends Token
{
    public TThis()
    {
        super.setText("this");
    }

    public TThis(int line, int pos)
    {
        super.setText("this");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TThis(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTThis(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TThis text.");
    }
}
