/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import java.util.*;
import joosc.analysis.*;

public final class ABlockSimplestm extends PSimplestm
{
    private TLBrace _lBrace_;
    private final LinkedList _stm_ = new TypedLinkedList(new Stm_Cast());
    private TRBrace _rBrace_;

    public ABlockSimplestm()
    {
    }

    public ABlockSimplestm(
        TLBrace _lBrace_,
        List _stm_,
        TRBrace _rBrace_)
    {
        setLBrace(_lBrace_);

        {
            this._stm_.clear();
            this._stm_.addAll(_stm_);
        }

        setRBrace(_rBrace_);

    }

    public ABlockSimplestm(
        TLBrace _lBrace_,
        XPStm _stm_,
        TRBrace _rBrace_)
    {
        setLBrace(_lBrace_);

        if(_stm_ != null)
        {
            while(_stm_ instanceof X1PStm)
            {
                this._stm_.addFirst(((X1PStm) _stm_).getPStm());
                _stm_ = ((X1PStm) _stm_).getXPStm();
            }
            this._stm_.addFirst(((X2PStm) _stm_).getPStm());
        }

        setRBrace(_rBrace_);

    }
    public Object clone()
    {
        return new ABlockSimplestm(
            (TLBrace) cloneNode(_lBrace_),
            cloneList(_stm_),
            (TRBrace) cloneNode(_rBrace_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlockSimplestm(this);
    }

    public TLBrace getLBrace()
    {
        return _lBrace_;
    }

    public void setLBrace(TLBrace node)
    {
        if(_lBrace_ != null)
        {
            _lBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lBrace_ = node;
    }

    public LinkedList getStm()
    {
        return _stm_;
    }

    public void setStm(List list)
    {
        _stm_.clear();
        _stm_.addAll(list);
    }

    public TRBrace getRBrace()
    {
        return _rBrace_;
    }

    public void setRBrace(TRBrace node)
    {
        if(_rBrace_ != null)
        {
            _rBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rBrace_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lBrace_)
            + toString(_stm_)
            + toString(_rBrace_);
    }

    void removeChild(Node child)
    {
        if(_lBrace_ == child)
        {
            _lBrace_ = null;
            return;
        }

        if(_stm_.remove(child))
        {
            return;
        }

        if(_rBrace_ == child)
        {
            _rBrace_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lBrace_ == oldChild)
        {
            setLBrace((TLBrace) newChild);
            return;
        }

        for(ListIterator i = _stm_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_rBrace_ == oldChild)
        {
            setRBrace((TRBrace) newChild);
            return;
        }

    }

    private class Stm_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PStm node = (PStm) o;

            if((node.parent() != null) &&
                (node.parent() != ABlockSimplestm.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ABlockSimplestm.this))
            {
                node.parent(ABlockSimplestm.this);
            }

            return node;
        }
    }
}
