/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import java.util.*;
import joosc.analysis.*;

public final class ACharCastExp extends PCastExp
{
    private TLPar _lPar_;
    private TChar _char_;
    private TRPar _rPar_;
    private PUnaryExp _unaryExp_;

    public ACharCastExp()
    {
    }

    public ACharCastExp(
        TLPar _lPar_,
        TChar _char_,
        TRPar _rPar_,
        PUnaryExp _unaryExp_)
    {
        setLPar(_lPar_);

        setChar(_char_);

        setRPar(_rPar_);

        setUnaryExp(_unaryExp_);

    }
    public Object clone()
    {
        return new ACharCastExp(
            (TLPar) cloneNode(_lPar_),
            (TChar) cloneNode(_char_),
            (TRPar) cloneNode(_rPar_),
            (PUnaryExp) cloneNode(_unaryExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACharCastExp(this);
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public TChar getChar()
    {
        return _char_;
    }

    public void setChar(TChar node)
    {
        if(_char_ != null)
        {
            _char_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _char_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public PUnaryExp getUnaryExp()
    {
        return _unaryExp_;
    }

    public void setUnaryExp(PUnaryExp node)
    {
        if(_unaryExp_ != null)
        {
            _unaryExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _unaryExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lPar_)
            + toString(_char_)
            + toString(_rPar_)
            + toString(_unaryExp_);
    }

    void removeChild(Node child)
    {
        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_char_ == child)
        {
            _char_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

        if(_unaryExp_ == child)
        {
            _unaryExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_char_ == oldChild)
        {
            setChar((TChar) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        if(_unaryExp_ == oldChild)
        {
            setUnaryExp((PUnaryExp) newChild);
            return;
        }

    }
}
