/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import java.util.*;
import joosc.analysis.*;

public final class ADeclStm extends PStm
{
    private final LinkedList _onelocal_ = new TypedLinkedList(new Onelocal_Cast());

    public ADeclStm()
    {
    }

    public ADeclStm(
        List _onelocal_)
    {
        {
            this._onelocal_.clear();
            this._onelocal_.addAll(_onelocal_);
        }

    }

    public ADeclStm(
        XPOnelocal _onelocal_)
    {
        if(_onelocal_ != null)
        {
            while(_onelocal_ instanceof X1POnelocal)
            {
                this._onelocal_.addFirst(((X1POnelocal) _onelocal_).getPOnelocal());
                _onelocal_ = ((X1POnelocal) _onelocal_).getXPOnelocal();
            }
            this._onelocal_.addFirst(((X2POnelocal) _onelocal_).getPOnelocal());
        }

    }
    public Object clone()
    {
        return new ADeclStm(
            cloneList(_onelocal_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclStm(this);
    }

    public LinkedList getOnelocal()
    {
        return _onelocal_;
    }

    public void setOnelocal(List list)
    {
        _onelocal_.clear();
        _onelocal_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_onelocal_);
    }

    void removeChild(Node child)
    {
        if(_onelocal_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _onelocal_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Onelocal_Cast implements Cast
    {
        public Object cast(Object o)
        {
            POnelocal node = (POnelocal) o;

            if((node.parent() != null) &&
                (node.parent() != ADeclStm.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ADeclStm.this))
            {
                node.parent(ADeclStm.this);
            }

            return node;
        }
    }
}
