/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import java.util.*;
import joosc.analysis.*;

public final class AInstanceofRelExp extends PRelExp
{
    private PRelExp _relExp_;
    private TInstanceof _instanceof_;
    private TIdentifier _identifier_;

    public AInstanceofRelExp()
    {
    }

    public AInstanceofRelExp(
        PRelExp _relExp_,
        TInstanceof _instanceof_,
        TIdentifier _identifier_)
    {
        setRelExp(_relExp_);

        setInstanceof(_instanceof_);

        setIdentifier(_identifier_);

    }
    public Object clone()
    {
        return new AInstanceofRelExp(
            (PRelExp) cloneNode(_relExp_),
            (TInstanceof) cloneNode(_instanceof_),
            (TIdentifier) cloneNode(_identifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstanceofRelExp(this);
    }

    public PRelExp getRelExp()
    {
        return _relExp_;
    }

    public void setRelExp(PRelExp node)
    {
        if(_relExp_ != null)
        {
            _relExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _relExp_ = node;
    }

    public TInstanceof getInstanceof()
    {
        return _instanceof_;
    }

    public void setInstanceof(TInstanceof node)
    {
        if(_instanceof_ != null)
        {
            _instanceof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _instanceof_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_relExp_)
            + toString(_instanceof_)
            + toString(_identifier_);
    }

    void removeChild(Node child)
    {
        if(_relExp_ == child)
        {
            _relExp_ = null;
            return;
        }

        if(_instanceof_ == child)
        {
            _instanceof_ = null;
            return;
        }

        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_relExp_ == oldChild)
        {
            setRelExp((PRelExp) newChild);
            return;
        }

        if(_instanceof_ == oldChild)
        {
            setInstanceof((TInstanceof) newChild);
            return;
        }

        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

    }
}
