/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import java.util.*;
import joosc.analysis.*;

public final class ATmpobjectReceiver extends PReceiver
{
    private PPostfixExp _postfixExp_;

    public ATmpobjectReceiver()
    {
    }

    public ATmpobjectReceiver(
        PPostfixExp _postfixExp_)
    {
        setPostfixExp(_postfixExp_);

    }
    public Object clone()
    {
        return new ATmpobjectReceiver(
            (PPostfixExp) cloneNode(_postfixExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATmpobjectReceiver(this);
    }

    public PPostfixExp getPostfixExp()
    {
        return _postfixExp_;
    }

    public void setPostfixExp(PPostfixExp node)
    {
        if(_postfixExp_ != null)
        {
            _postfixExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _postfixExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_postfixExp_);
    }

    void removeChild(Node child)
    {
        if(_postfixExp_ == child)
        {
            _postfixExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_postfixExp_ == oldChild)
        {
            setPostfixExp((PPostfixExp) newChild);
            return;
        }

    }
}
