/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import java.util.*;
import joosc.analysis.*;

public final class ATmpField extends PField
{
    private TProtected _protected_;
    private PType _type_;
    private PIdentifierList _identifierList_;
    private TSemicolon _semicolon_;

    public ATmpField()
    {
    }

    public ATmpField(
        TProtected _protected_,
        PType _type_,
        PIdentifierList _identifierList_,
        TSemicolon _semicolon_)
    {
        setProtected(_protected_);

        setType(_type_);

        setIdentifierList(_identifierList_);

        setSemicolon(_semicolon_);

    }
    public Object clone()
    {
        return new ATmpField(
            (TProtected) cloneNode(_protected_),
            (PType) cloneNode(_type_),
            (PIdentifierList) cloneNode(_identifierList_),
            (TSemicolon) cloneNode(_semicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATmpField(this);
    }

    public TProtected getProtected()
    {
        return _protected_;
    }

    public void setProtected(TProtected node)
    {
        if(_protected_ != null)
        {
            _protected_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _protected_ = node;
    }

    public PType getType()
    {
        return _type_;
    }

    public void setType(PType node)
    {
        if(_type_ != null)
        {
            _type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _type_ = node;
    }

    public PIdentifierList getIdentifierList()
    {
        return _identifierList_;
    }

    public void setIdentifierList(PIdentifierList node)
    {
        if(_identifierList_ != null)
        {
            _identifierList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifierList_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return _semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(_semicolon_ != null)
        {
            _semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _semicolon_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_protected_)
            + toString(_type_)
            + toString(_identifierList_)
            + toString(_semicolon_);
    }

    void removeChild(Node child)
    {
        if(_protected_ == child)
        {
            _protected_ = null;
            return;
        }

        if(_type_ == child)
        {
            _type_ = null;
            return;
        }

        if(_identifierList_ == child)
        {
            _identifierList_ = null;
            return;
        }

        if(_semicolon_ == child)
        {
            _semicolon_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_protected_ == oldChild)
        {
            setProtected((TProtected) newChild);
            return;
        }

        if(_type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(_identifierList_ == oldChild)
        {
            setIdentifierList((PIdentifierList) newChild);
            return;
        }

        if(_semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

    }
}
