/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

public final class X1PArgumentListTail extends XPArgumentListTail
{
    private XPArgumentListTail _xPArgumentListTail_;
    private PArgumentListTail _pArgumentListTail_;

    public X1PArgumentListTail()
    {
    }

    public X1PArgumentListTail(
        XPArgumentListTail _xPArgumentListTail_,
        PArgumentListTail _pArgumentListTail_)
    {
        setXPArgumentListTail(_xPArgumentListTail_);
        setPArgumentListTail(_pArgumentListTail_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPArgumentListTail getXPArgumentListTail()
    {
        return _xPArgumentListTail_;
    }

    public void setXPArgumentListTail(XPArgumentListTail node)
    {
        if(_xPArgumentListTail_ != null)
        {
            _xPArgumentListTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPArgumentListTail_ = node;
    }

    public PArgumentListTail getPArgumentListTail()
    {
        return _pArgumentListTail_;
    }

    public void setPArgumentListTail(PArgumentListTail node)
    {
        if(_pArgumentListTail_ != null)
        {
            _pArgumentListTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pArgumentListTail_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPArgumentListTail_ == child)
        {
            _xPArgumentListTail_ = null;
        }

        if(_pArgumentListTail_ == child)
        {
            _pArgumentListTail_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPArgumentListTail_) +
            toString(_pArgumentListTail_);
    }
}
