/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

public final class X1PFormal extends XPFormal
{
    private XPFormal _xPFormal_;
    private PFormal _pFormal_;

    public X1PFormal()
    {
    }

    public X1PFormal(
        XPFormal _xPFormal_,
        PFormal _pFormal_)
    {
        setXPFormal(_xPFormal_);
        setPFormal(_pFormal_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPFormal getXPFormal()
    {
        return _xPFormal_;
    }

    public void setXPFormal(XPFormal node)
    {
        if(_xPFormal_ != null)
        {
            _xPFormal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPFormal_ = node;
    }

    public PFormal getPFormal()
    {
        return _pFormal_;
    }

    public void setPFormal(PFormal node)
    {
        if(_pFormal_ != null)
        {
            _pFormal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pFormal_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPFormal_ == child)
        {
            _xPFormal_ = null;
        }

        if(_pFormal_ == child)
        {
            _pFormal_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPFormal_) +
            toString(_pFormal_);
    }
}
