/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

public final class X1PMethod extends XPMethod
{
    private XPMethod _xPMethod_;
    private PMethod _pMethod_;

    public X1PMethod()
    {
    }

    public X1PMethod(
        XPMethod _xPMethod_,
        PMethod _pMethod_)
    {
        setXPMethod(_xPMethod_);
        setPMethod(_pMethod_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPMethod getXPMethod()
    {
        return _xPMethod_;
    }

    public void setXPMethod(XPMethod node)
    {
        if(_xPMethod_ != null)
        {
            _xPMethod_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPMethod_ = node;
    }

    public PMethod getPMethod()
    {
        return _pMethod_;
    }

    public void setPMethod(PMethod node)
    {
        if(_pMethod_ != null)
        {
            _pMethod_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pMethod_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPMethod_ == child)
        {
            _xPMethod_ = null;
        }

        if(_pMethod_ == child)
        {
            _pMethod_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPMethod_) +
            toString(_pMethod_);
    }
}
