/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

public final class X1POnefield extends XPOnefield
{
    private XPOnefield _xPOnefield_;
    private POnefield _pOnefield_;

    public X1POnefield()
    {
    }

    public X1POnefield(
        XPOnefield _xPOnefield_,
        POnefield _pOnefield_)
    {
        setXPOnefield(_xPOnefield_);
        setPOnefield(_pOnefield_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPOnefield getXPOnefield()
    {
        return _xPOnefield_;
    }

    public void setXPOnefield(XPOnefield node)
    {
        if(_xPOnefield_ != null)
        {
            _xPOnefield_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPOnefield_ = node;
    }

    public POnefield getPOnefield()
    {
        return _pOnefield_;
    }

    public void setPOnefield(POnefield node)
    {
        if(_pOnefield_ != null)
        {
            _pOnefield_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pOnefield_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPOnefield_ == child)
        {
            _xPOnefield_ = null;
        }

        if(_pOnefield_ == child)
        {
            _pOnefield_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPOnefield_) +
            toString(_pOnefield_);
    }
}
