/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

public final class X2POnelocal extends XPOnelocal
{
    private POnelocal _pOnelocal_;

    public X2POnelocal()
    {
    }

    public X2POnelocal(
        POnelocal _pOnelocal_)
    {
        setPOnelocal(_pOnelocal_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public POnelocal getPOnelocal()
    {
        return _pOnelocal_;
    }

    public void setPOnelocal(POnelocal node)
    {
        if(_pOnelocal_ != null)
        {
            _pOnelocal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pOnelocal_ = node;
    }

    void removeChild(Node child)
    {
        if(_pOnelocal_ == child)
        {
            _pOnelocal_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pOnelocal_);
    }
}
