/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

public final class X2PStm extends XPStm
{
    private PStm _pStm_;

    public X2PStm()
    {
    }

    public X2PStm(
        PStm _pStm_)
    {
        setPStm(_pStm_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PStm getPStm()
    {
        return _pStm_;
    }

    public void setPStm(PStm node)
    {
        if(_pStm_ != null)
        {
            _pStm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pStm_ = node;
    }

    void removeChild(Node child)
    {
        if(_pStm_ == child)
        {
            _pStm_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pStm_);
    }
}
