/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

public final class X2TImportpath extends XTImportpath
{
    private TImportpath _tImportpath_;

    public X2TImportpath()
    {
    }

    public X2TImportpath(
        TImportpath _tImportpath_)
    {
        setTImportpath(_tImportpath_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public TImportpath getTImportpath()
    {
        return _tImportpath_;
    }

    public void setTImportpath(TImportpath node)
    {
        if(_tImportpath_ != null)
        {
            _tImportpath_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tImportpath_ = node;
    }

    void removeChild(Node child)
    {
        if(_tImportpath_ == child)
        {
            _tImportpath_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_tImportpath_);
    }
}
